Scheduler Class Reference
#include <Scheduler.h>
Public Member Functions
Scheduler (const std::string &in_file, const unsigned int &num_threads)
Scheduler (const Scheduler &other)
Scheduler & operator= (const Scheduler &other)
void initialize (const unsigned int &num_threads, const bool &RL_active_reshuffling, const bool &RL_performance_reshuffling, const double &step_size, const double &LAMBDA, const double &sched_period, const bool &suspend_threads, const bool &printout_strategies, const bool &printout_actions, const bool &write_to_files, const bool &write_to_files_details, const double &gamma, const bool &OS_mapping, const bool &RL_mapping, const bool &PR_mapping, const bool &ST_mapping, const bool &optimize_main_resource)
void update (const unsigned int &resource_ind, std::vector< bool > &update_inds)
void run ()
void retrieve_performances (const unsigned int &resource_ind)
void performance_preprocessing (const unsigned int &resource_ind)
void apply_scheduling_policy ()
thread_info * get_tinfo (void)
const unsigned int & get_number_threads (void) const
Static Public Member Functions
static void * send_wrapper (void *object)
Public Attributes
unsigned int counter_of_threads_
Detailed Description
Scheduler
Definition at line 36 of file Scheduler.h.
Constructor & Destructor Documentation
Scheduler::Scheduler (const std::string & in_file, const unsigned int & num_threads)
The first part defines the number of NUMA nodes that should be used for pinning
The first pair defines the number of CPU nodes that should be used for pinning from each NUMA node
NON-ADJUSTABLE PARAMETERS (Please, do not change the following)
Definition at line 274 of file Scheduler.cpp.
Member Function Documentation
void Scheduler::apply_scheduling_policy ()
Applying scheduling policy
Definition at line 1535 of file Scheduler.cpp.
Referenced by run().
const unsigned int& Scheduler::get_number_threads (void) const [inline]
Get number of threads
Returns
Definition at line 139 of file Scheduler.h.
thread_info* Scheduler::get_tinfo (void) [inline]
Get information of thread
Returns
Definition at line 122 of file Scheduler.h.
void Scheduler::initialize (const unsigned int & num_threads, const bool & RL_active_reshuffling, const bool & RL_performance_reshuffling, const double & step_size, const double & LAMBDA, const double & sched_period, const bool & suspend_threads, const bool & printout_strategies, const bool & printout_actions, const bool & write_to_files, const bool & write_to_files_details, const double & gamma, const bool & OS_mapping, const bool & RL_mapping, const bool & PR_mapping, const bool & ST_mapping, const bool & optimize_main_resource)
Initialize Scheduler
Parameters
num_threads Number of threads
RL_active_reshuffling Reshuffle RL strategies if active threads have changed
RL_performance_reshuffling Reshuffle RL strategies if performance of active threads has dropped significantly
step_size Step size of RL algorithm
LAMBDA Perturbation factor of RL algorithm
sched_period Scheduling period of the child resources
suspend_threads Suspend threads when switching NUMA nodes
printout_strategies
printout_actions
write_to_files
write_to_files_details
gamma Factor related to the definition of the balanced performance indicator
OS_mapping Mapping according to the OS scheduler
RL_mapping Mapping according to the RL scheduler
PR_mapping Mapping according to a predefined map
ST_mapping Perform also allocation of thread memory
optimize_main_resource Optimize the use of NUMA nodes
void Scheduler::performance_preprocessing (const unsigned int & resource_ind)
Preprocessing of performances
Parameters
resource_ind
Definition at line 1364 of file Scheduler.cpp.
References Struct_OverallPerformance::update_ave_balanced_performance_per_main_resource(), Struct_OverallPerformance::update_ave_balanced_performances_per_main_resource_per_action(), Struct_OverallPerformance::update_ave_performance_per_main_resource(), Struct_OverallPerformance::update_num_threads_using_main_resource_per_action(), Struct_OverallPerformance::update_run_average_balanced_performance_per_main_resource(), Struct_OverallPerformance::update_run_average_balanced_performances_per_main_resource_per_action(), Struct_OverallPerformance::update_run_average_performance_per_main_resource(), Struct_OverallPerformance::update_sum_balanced_performances_per_main_resource(), Struct_OverallPerformance::update_sum_balanced_performances_per_main_resource_per_action(), and Struct_OverallPerformance::update_sum_performances_per_main_resource().
Referenced by run().
void Scheduler::retrieve_performances (const unsigned int & resource_ind)
Retrieve performances
Parameters
resource_ind
Definition at line 1298 of file Scheduler.cpp.
References ThreadControl::thd_record_counters().
Referenced by run().
void Scheduler::run ()
Run scheduler
Parameters
num_threads
rl_mapping NON-ADJUSTABLE PARAMETERS (Please, do not change the following) Parameters w.r.t. the RL_mapping algorithm
Definition at line 856 of file Scheduler.cpp.
References apply_scheduling_policy(), performance_preprocessing(), retrieve_performances(), and update().
void Scheduler::update (const unsigned int & resource_ind, std::vector< bool > & update_inds)
Update scheduling decisions
Parameters
resource_ind
update_inds
Definition at line 924 of file Scheduler.cpp.
Referenced by run().
The documentation for this class was generated from the following files:
Scheduler.h
Scheduler.cpp