Struct_MethodsOptimize Struct Reference
#include <MethodsOptimize.h>
Public Member Functions
void RL_optimize (const std::vector< double > &vec_cummulative_estimates, const unsigned int &num_choices, unsigned int &action, const double &LAMBDA, const double &current_run_ave_performance)
unsigned int random_selection_uniform (const unsigned int &num_choices)
unsigned int random_selection_strategy (const unsigned int &num_choices, const std::vector< double > &estimates)
void AL_optimize (const bool &random_switch, const bool &action_change, const double &run_average_balanced_performance, const std::vector< double > &run_ave_performance_per_main_resource, const double &low_benchmark, const double &high_benchmark, unsigned int &action, unsigned int &num_actions, const double &LAMBDA, const unsigned int &thread, const double &numa_switch_threshold)
Detailed Description
It provides the necessary functions/algorithms for optimizing the selection of resources from the threads. It may or may not make use of the estimates over the most rewarding resources, as created by the MethodsEstimate.h library.
Definition at line 24 of file MethodsOptimize.h.
Member Function Documentation
void Struct_MethodsOptimize::AL_optimize (const bool & random_switch, const bool & action_change, const double & run_average_balanced_performance, const std::vector< double > & run_ave_performance_per_main_resource, const double & low_benchmark, const double & high_benchmark, unsigned int & action, unsigned int & num_actions, const double & LAMBDA, const unsigned int & thread, const double & numa_switch_threshold) [inline]
It provides a framework for computing the optimal allocation of resources based on Aspiration Learning
Parameters
random_switch Indicator that a Random Switch should be executed
action_change Indicator that the action should be changed
run_average_balanced_performance Running average balanced performance
run_ave_performance_per_main_resource Running average performance per main resource
low_benchmark Low benchmark of aspiration learning
high_benchmark High benchmark of aspiration learning
action Action
num_actions Number of actions
LAMBDA Perturbation factor
thread Thread indicator
numa_switch_threshold Threshold over which the NUMA (main resource) is updated
Definition at line 143 of file MethodsOptimize.h.
References random_selection_uniform().
unsigned int Struct_MethodsOptimize::random_selection_strategy (const unsigned int & num_choices, const std::vector< double > & estimates) [inline]
Random Selection Strategy assigns a random selection based on the provided estimates
Parameters
num_choices
estimates
Returns
Definition at line 94 of file MethodsOptimize.h.
Referenced by RL_optimize().
unsigned int Struct_MethodsOptimize::random_selection_uniform (const unsigned int & num_choices) [inline]
Random selection of resources based on a uniform distribution
Parameters
num_choices available number of choices
Returns
Definition at line 64 of file MethodsOptimize.h.
Referenced by AL_optimize(), and RL_optimize().
void Struct_MethodsOptimize::RL_optimize (const std::vector< double > & vec_cummulative_estimates, const unsigned int & num_choices, unsigned int & action, const double & LAMBDA, const double & current_run_ave_performance) [inline]
Provides a framework for computing the optimal allocation of resources based on the estimates created by an RL estimator.
Parameters
vec_cummulative_estimates vector of cummulative estimates
num_choices number of choices
action action
LAMBDA perturbation factor
current_run_ave_performance current running average performance
Definition at line 36 of file MethodsOptimize.h.
References random_selection_strategy(), and random_selection_uniform().
The documentation for this struct was generated from the following file:
MethodsOptimize.h