Struct_Estimate Struct Reference
#include <MethodsEstimate.h>
Public Member Functions
void initialize (const std::string &resource, const unsigned int &num_sources, const unsigned int &max_num_sources_user, const unsigned int &initial_action, const bool &mixed)
void initialize_w_child (const std::string &resource, const unsigned int &num_sources, const unsigned int &max_num_sources_user, const std::string &child_resource, const std::vector< std::vector< unsigned int > > &vec_num_child_sources, const std::vector< unsigned int > &vec_max_num_child_sources_user, const unsigned int &thread_num)
void update_estimates (const std::vector< double > &vec_estimates)
void update_child_estimate (const std::vector< double > &vec_estimates, const unsigned int &source_num)
void update_action (const std::vector< double > &vec_estimates, const unsigned int &source_num)
Public Attributes
std::string resource_
unsigned int num_sources_
std::vector< std::vector
*
< unsigned int > > vec_child_sources_
std::vector< double > vec_estimates_
std::vector< double > vec_cummulative_estimates_
double run_average_performance_
std::vector< Struct_Estimate > vec_child_estimates_
double low_benchmark_
double high_benchmark_
double maximum_performance_
bool random_switch_
bool action_change_
Detailed Description
Struct_Estimate
It provides the necessary information for keeping track our estimates for the performance of a thread over a specific node/cpu or the performance of a thread's memory over a specific node (or some further refinement if possible)
This structure is planned for 'per-thread' use, since it will hold estimates over the proper use of resources by each thread separately.
Within this structure, there is an additional struct that tracks the performances of the threads throughout the running time.
Definition at line 43 of file MethodsEstimate.h.
Member Function Documentation
void Struct_Estimate::initialize (const std::string & resource, const unsigned int & num_sources, const unsigned int & max_num_sources_user, const unsigned int & initial_action, const bool & mixed) [inline]
This function initializes the structure
Parameters
resource resource type
num_sources number of sources
max_num_sources_user maximum number of sources per user
initial_action initial action
mixed
Definition at line 74 of file MethodsEstimate.h.
Referenced by initialize_w_child().
void Struct_Estimate::initialize_w_child (const std::string & resource, const unsigned int & num_sources, const unsigned int & max_num_sources_user, const std::string & child_resource, const std::vector< std::vector< unsigned int > > & vec_num_child_sources, const std::vector< unsigned int > & vec_max_num_child_sources_user, const unsigned int & thread_num) [inline]
It is implicitly assumed that the main resource also has a child resource For example, in the case of PROCESSING_BANDWIDTH, the main sources correspond to the NUMA nodes (if available) while the child sources correspond to the CPU units available in each NUMA node.
Parameters
resource resource type
num_sources number of sources
max_num_sources_user maximum number of sources per user
child_resource child resource type
vec_num_child_sources vector of number of child sources
vec_max_num_child_sources_user vector of maximum number of child sources per user
thread_num thread number
Definition at line 129 of file MethodsEstimate.h.
References Struct_Actions::compute_initial_action(), and initialize().
void Struct_Estimate::update_action (const std::vector< double > & vec_estimates, const unsigned int & source_num) [inline]
Parameters
vec_estimates
source_num
Definition at line 225 of file MethodsEstimate.h.
void Struct_Estimate::update_child_estimate (const std::vector< double > & vec_estimates, const unsigned int & source_num) [inline]
This function receives a vector of estimates for the child resources, and assigns it to the existing structure
Parameters
vec_estimates
source_num
Definition at line 213 of file MethodsEstimate.h.
void Struct_Estimate::update_estimates (const std::vector< double > & vec_estimates) [inline]
This function receives a vector of estimates, and assigns it to the existing structure
Parameters
vec_estimates
Definition at line 201 of file MethodsEstimate.h.
The documentation for this struct was generated from the following file:
MethodsEstimate.h