Struct_Actions Struct Reference
#include <MethodsActions.h>
Public Member Functions
void initialize (const std::string &resource, const unsigned int &num_sources, const unsigned int &max_num_sources_user, std::vector< unsigned int > &action_main_old, const unsigned int &thread_num)
void initialize_w_child (const std::string &resource, const unsigned int &num_sources, const unsigned int &max_num_sources_user, const std::string &child_resource, const std::vector< std::vector< unsigned int > > &vec_num_child_sources, const std::vector< unsigned int > &vec_max_num_child_sources_user, const unsigned int &thread_num, std::vector< unsigned int > &action_main_old, const unsigned int &policy, const unsigned int &neighborhood_size)
std::vector< unsigned int > compute_initial_action (const std::vector< std::vector< unsigned int > > &vec_num_child_sources, const std::vector< unsigned int > &vec_max_num_child_sources_user, const unsigned int &thread_num, const unsigned int &max_number_available_main_sources)
std::vector< unsigned int > compute_initial_action_rr (const std::vector< std::vector< unsigned int > > &vec_num_child_sources, const std::vector< unsigned int > &vec_max_num_child_sources_user, const unsigned int &thread_num)
Public Attributes
std::string resource_
std::string child_resource_
unsigned int num_actions_main_resource_
std::vector< unsigned int > vec_num_child_actions_per_main_resource_
std::map< std::tuple< unsigned
*
int, unsigned int, unsigned
*
int >, std::vector< unsigned
*
int > > map_neighbors_
unsigned int action_per_main_source_
unsigned int previous_action_per_main_source_
unsigned int action_per_child_source_
unsigned int previous_action_per_child_source_
std::vector< std::vector
*
< unsigned int > > vec_child_sources_
Detailed Description
This structure gathers information that is relevant for keeping in track the actions selected by each thread with respect to the resources that need to be optimized (e.g., cpu placement, memory placement)
Definition at line 23 of file MethodsActions.h.
Member Function Documentation
std::vector<unsigned int> Struct_Actions::compute_initial_action (const std::vector< std::vector< unsigned int > > & vec_num_child_sources, const std::vector< unsigned int > & vec_max_num_child_sources_user, const unsigned int & thread_num, const unsigned int & max_number_available_main_sources) [inline]
Compute initial action
Parameters
vec_num_child_sources vector of number of child sources
vec_max_num_child_sources_user vector of maximum number of child sources
thread_num thread number
max_number_available_main_sources maximum number of available main sources
Returns
Definition at line 185 of file MethodsActions.h.
Referenced by initialize_w_child(), and Struct_Estimate::initialize_w_child().
std::vector<unsigned int> Struct_Actions::compute_initial_action_rr (const std::vector< std::vector< unsigned int > > & vec_num_child_sources, const std::vector< unsigned int > & vec_max_num_child_sources_user, const unsigned int & thread_num) [inline]
Compute initial action with Round Robin algorithm
Parameters
vec_num_child_sources vector of number of child sources
vec_max_num_child_sources_user vector of maximum number of child sources per user
thread_num thread number
Returns
Definition at line 241 of file MethodsActions.h.
Referenced by initialize_w_child().
void Struct_Actions::initialize (const std::string & resource, const unsigned int & num_sources, const unsigned int & max_num_sources_user, std::vector< unsigned int > & action_main_old, const unsigned int & thread_num) [inline]
We initialize the structure Struct_Actions
Parameters
resource resource type
num_sources number of sources
max_num_sources_user maximum number of sources
action_main_old old action of the main resource
thread_num thread number
Definition at line 61 of file MethodsActions.h.
void Struct_Actions::initialize_w_child (const std::string & resource, const unsigned int & num_sources, const unsigned int & max_num_sources_user, const std::string & child_resource, const std::vector< std::vector< unsigned int > > & vec_num_child_sources, const std::vector< unsigned int > & vec_max_num_child_sources_user, const unsigned int & thread_num, std::vector< unsigned int > & action_main_old, const unsigned int & policy, const unsigned int & neighborhood_size) [inline]
Initialize the performance tracking variables when child resources are also present.
Parameters
resource type of resource
num_sources number of sources
max_num_sources_user maximum number of sources
child_resource type of child resource
vec_num_child_sources vector of number of child sources per main source
vec_max_num_child_sources_user vector of maximum number of child sources per main source
thread_num thread number
action_main_old old action of the main resource
policy policy
neighborhood_size neighborhood size (for considering groups of child sources)
Definition at line 93 of file MethodsActions.h.
References compute_initial_action(), and compute_initial_action_rr().
The documentation for this struct was generated from the following file:
MethodsActions.h