Struct_OverallPerformance Struct Reference
#include <MethodsPerformanceMonitoring.h>
Public Member Functions
void initialize (const unsigned int &num_main_resources, const std::vector< unsigned int > &num_actions)
void update_sum_performances_per_main_resource (const unsigned int &resource_ind, const double &sum_performances)
void update_ave_performance_per_main_resource (const unsigned int &resource_ind, const double &ave_performance)
void update_sum_balanced_performances_per_main_resource (const unsigned int &resource_ind, const double &sum_balanced_performances)
void update_ave_balanced_performance_per_main_resource (const unsigned int &resource_ind, const double &ave_balanced_performance)
void update_run_average_performance_per_main_resource (const unsigned int &resource_ind, const double &ave_performance, const unsigned int &iteration)
void update_run_average_balanced_performance_per_main_resource (const unsigned int &resource_ind, const double ave_balanced_performance, const unsigned int &iteration)
void update_sum_balanced_performances_per_main_resource_per_action (const unsigned int &resource_ind, const std::vector< double > &sum_performances)
void update_ave_balanced_performances_per_main_resource_per_action (const unsigned int &resource_ind, const std::vector< double > &ave_performances)
void update_num_threads_using_main_resource_per_action (const unsigned int &resource_ind, const std::vector< unsigned int > &vec_threads)
void update_run_average_balanced_performances_per_main_resource_per_action (const unsigned int &resource_ind, const unsigned int &action, const double &ave_balanced_performance, const unsigned int &iteration)
Public Attributes
std::vector< double > sum_performances_per_main_resource_
std::vector< double > sum_balanced_performances_per_main_resource_
std::vector< double > ave_performance_per_main_resource_
std::vector< double > ave_balanced_performance_per_main_resource_
std::vector< std::vector
*
< double > > sum_balanced_performances_per_main_resource_per_action_
std::vector< std::vector
*
< double > > ave_balanced_performances_per_main_resource_per_action_
std::vector< std::vector
*
< unsigned int > > num_threads_using_main_resource_per_action_
std::vector< std::vector
*
< double > > run_ave_balanced_performances_per_main_resource_per_action_
std::vector< double > run_average_performance_
std::vector< double > run_average_balanced_performance_
Detailed Description
The role of this structure is to gather some overall information regarding the performance of the threads e.g., the sum of the performances of the threads
Definition at line 21 of file MethodsPerformanceMonitoring.h.
Member Function Documentation
void Struct_OverallPerformance::update_ave_balanced_performance_per_main_resource (const unsigned int & resource_ind, const double & ave_balanced_performance) [inline]
Update average balanced performances per main resource
Parameters
resource_ind
ave_balanced_performance
Definition at line 125 of file MethodsPerformanceMonitoring.h.
Referenced by Scheduler::performance_preprocessing().
void Struct_OverallPerformance::update_ave_balanced_performances_per_main_resource_per_action (const unsigned int & resource_ind, const std::vector< double > & ave_performances) [inline]
Update average balanced performances per main resource and per action
Parameters
resource_ind
ave_performances
Definition at line 194 of file MethodsPerformanceMonitoring.h.
Referenced by Scheduler::performance_preprocessing().
void Struct_OverallPerformance::update_ave_performance_per_main_resource (const unsigned int & resource_ind, const double & ave_performance) [inline]
Update average performance per main resource
Parameters
resource_ind
ave_performance
Definition at line 103 of file MethodsPerformanceMonitoring.h.
Referenced by Scheduler::performance_preprocessing().
void Struct_OverallPerformance::update_num_threads_using_main_resource_per_action (const unsigned int & resource_ind, const std::vector< unsigned int > & vec_threads) [inline]
Update number of threads using main resource per action
Parameters
resource_ind
vec_threads
Definition at line 205 of file MethodsPerformanceMonitoring.h.
Referenced by Scheduler::performance_preprocessing().
void Struct_OverallPerformance::update_run_average_balanced_performance_per_main_resource (const unsigned int & resource_ind, const double ave_balanced_performance, const unsigned int & iteration) [inline]
Update running average balanced performances per main resource
Parameters
resource_ind
ave_balanced_performance
iteration
Definition at line 161 of file MethodsPerformanceMonitoring.h.
Referenced by Scheduler::performance_preprocessing().
void Struct_OverallPerformance::update_run_average_balanced_performances_per_main_resource_per_action (const unsigned int & resource_ind, const unsigned int & action, const double & ave_balanced_performance, const unsigned int & iteration) [inline]
Update running average balanced performances per main resource and per action
Parameters
resource_ind
action
ave_balanced_performance
iteration
Here, we calculate the running average resource for each one of the actions of the main resource.
Definition at line 218 of file MethodsPerformanceMonitoring.h.
Referenced by Scheduler::performance_preprocessing().
void Struct_OverallPerformance::update_run_average_performance_per_main_resource (const unsigned int & resource_ind, const double & ave_performance, const unsigned int & iteration) [inline]
Update running average performances per main resource
Parameters
resource_ind
ave_performance
iteration
Definition at line 137 of file MethodsPerformanceMonitoring.h.
Referenced by Scheduler::performance_preprocessing().
void Struct_OverallPerformance::update_sum_balanced_performances_per_main_resource (const unsigned int & resource_ind, const double & sum_balanced_performances) [inline]
Update sum of balanced performances per main resource
Parameters
resource_ind
sum_balanced_performances
Definition at line 114 of file MethodsPerformanceMonitoring.h.
Referenced by Scheduler::performance_preprocessing().
void Struct_OverallPerformance::update_sum_balanced_performances_per_main_resource_per_action (const unsigned int & resource_ind, const std::vector< double > & sum_performances) [inline]
Update sum of balanced performances per main resource and per action
Parameters
resource_ind
sum_performances
Definition at line 183 of file MethodsPerformanceMonitoring.h.
Referenced by Scheduler::performance_preprocessing().
void Struct_OverallPerformance::update_sum_performances_per_main_resource (const unsigned int & resource_ind, const double & sum_performances) [inline]
Update sum of performances per main resource
Parameters
resource_ind
sum_performances
Definition at line 92 of file MethodsPerformanceMonitoring.h.
Referenced by Scheduler::performance_preprocessing().
The documentation for this struct was generated from the following file:
MethodsPerformanceMonitoring.h