.TH "Performance" 3 "Tue Jan 18 2022" "PaRLSched" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Performance \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PerformanceCounters\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBreset\fP (void)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnum_performance_counters\fP"
.br
.ti -1c
.RI "double \fBinitial_tot_ins\fP"
.br
.ti -1c
.RI "double \fBinitial_tot_cyc\fP"
.br
.ti -1c
.RI "double \fBinitial_lst_ins\fP"
.br
.ti -1c
.RI "double \fBinitial_L1misses\fP"
.br
.ti -1c
.RI "double \fBinitial_tlb_dm\fP"
.br
.ti -1c
.RI "double \fBtime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This structure captures different performance indicators of a thread 
.PP
Definition at line 23 of file PerformanceCounters\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PaRLSched from the source code\&.
