.TH "PerformanceCounters" 3 "Tue Jan 18 2022" "PaRLSched" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PerformanceCounters \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PerformanceCounters\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPerformanceCounters\fP ()"
.br
.ti -1c
.RI "\fB~PerformanceCounters\fP ()"
.br
.ti -1c
.RI "int \fBinitialize\fP (void)"
.br
.ti -1c
.RI "void \fBget_performance\fP (\fBPerformance\fP &performance)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBPerformanceCounters\fP 
.PP
Definition at line 49 of file PerformanceCounters\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PerformanceCounters::PerformanceCounters (void)"
Constructor of \fBPerformanceCounters\fP 
.PP
Definition at line 16 of file PerformanceCounters\&.cpp\&.
.SS "PerformanceCounters::~PerformanceCounters (void)"
Destructor of \fBPerformanceCounters\fP 
.PP
Definition at line 25 of file PerformanceCounters\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void PerformanceCounters::get_performance (\fBPerformance\fP &performance)"
Getting performance from \fBPerformanceCounters\fP
.PP
\fBParameters:\fP
.RS 4
\fIperformance\fP 
.RE
.PP

.PP
Definition at line 75 of file PerformanceCounters\&.cpp\&.
.SS "int PerformanceCounters::initialize (void)"
Initializing \fBPerformanceCounters\fP 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 34 of file PerformanceCounters\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PaRLSched from the source code\&.
