.TH "thread_info" 3 "Tue Jan 18 2022" "PaRLSched" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thread_info \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "pthread_t \fBreturn_thread_id\fP (void)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "pthread_t \fBthread_id\fP"
.br
.ti -1c
.RI "unsigned long int \fBpapi_thread_id\fP"
.br
.ti -1c
.RI "int \fBthread_num\fP"
.br
.ti -1c
.RI "char * \fBargv_string\fP"
.br
.ti -1c
.RI "int long \fBtotal_instructions_completed\fP"
.br
.ti -1c
.RI "bool \fBstatus\fP"
.br
.ti -1c
.RI "double \fBtermination_time\fP"
.br
.ti -1c
.RI "unsigned int \fBthread_goal\fP"
.br
.ti -1c
.RI "unsigned int \fBthread_ref\fP"
.br
.ti -1c
.RI "double \fBperformance\fP"
.br
.ti -1c
.RI "double \fBperformance_before\fP"
.br
.ti -1c
.RI "bool \fBperformance_update_ind\fP"
.br
.ti -1c
.RI "double \fBtotal_completed_ins_\fP"
.br
.ti -1c
.RI "double \fBtotal_completed_ins_before_\fP"
.br
.ti -1c
.RI "double \fBtotal_completed_ins_update_ind\fP"
.br
.ti -1c
.RI "double \fBtotal_cyc_\fP"
.br
.ti -1c
.RI "double \fBtotal_cyc_before_\fP"
.br
.ti -1c
.RI "double \fBtotal_cyc_update_ind\fP"
.br
.ti -1c
.RI "double \fBloadstore_ins_\fP"
.br
.ti -1c
.RI "double \fBloadstore_ins_before_\fP"
.br
.ti -1c
.RI "double \fBloadstore_ins_update_index_\fP"
.br
.ti -1c
.RI "double \fBL1misses_\fP"
.br
.ti -1c
.RI "double \fBL1misses_before_\fP"
.br
.ti -1c
.RI "double \fBL1misses_update_index_\fP"
.br
.ti -1c
.RI "double \fBtlb_dm_\fP"
.br
.ti -1c
.RI "double \fBtlb_dm_before_\fP"
.br
.ti -1c
.RI "double \fBtlb_dm_update_index_\fP"
.br
.ti -1c
.RI "double \fBtime_init\fP"
.br
.ti -1c
.RI "double \fBtime_before\fP"
.br
.ti -1c
.RI "double \fBtime\fP"
.br
.ti -1c
.RI "int \fBEVENT_SET\fP"
.br
.ti -1c
.RI "pid_t \fBtid\fP"
.br
.ti -1c
.RI "pid_t \fBpid\fP"
.br
.ti -1c
.RI "unsigned int \fBmemory_index\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file ThreadInfo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PaRLSched from the source code\&.
