.TH "PerformanceCounters" 3 "Mon Nov 29 2021" "PaRLSchedv1.0" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PerformanceCounters \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBinitialize\fP (void)"
.br
.ti -1c
.RI "void \fBget_performance\fP (\fBPerformance\fP &performance)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file PerformanceCounters\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PaRLSchedv1\&.0 from the source code\&.
